server:
  loc: bonc
debug: false
security:
  basic:
    enabled: false
  user:
    password: ltl
    name: ltl 
spring:
  datasource:
    bonc:
      driver-class-name: com.mysql.jdbc.Driver
      password: boncmysql
      url: jdbc:mysql://192.168.1.123:3306/test01
      username: root
    home:
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/sp02
      username: root    
    filters: stat,wall,log4j
  redis:
    host: localhost
    port: 6379
    database: 0
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

