debug: false
security:
  basic:
    enabled: false
  user:
    password: ltl
    name: ltl 
spring:
  profiles:
    active: home    
  redis:
    host: localhost
    port: 6379
    database: 0
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

