debug: false
security:
  basic:
    enabled: false
  user:
    password: ltl
    name: ltl 
spring:
  profiles:
    active: bonc    
  redis:
    host: localhost
    port: 6379
    database: 0
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

